spring:
  application:
    name: ai-mcp-heat-point-analyse
    version: 1.0.0
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: ${spring.application.version}
  main:
    banner-mode: off
logging:
  charset:
    file: UTF-8
  file:
    name: ${spring.application.name}:${spring.application.version}_log.log

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8081


heat-point:
  base-url: https://weibo.com
  
