spring:
  application:
    name: ai-mcp-heat-point-analyse
    version: 1.0.0
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: ${spring.application.version}
  main:
    banner-mode: off
logging:
  charset:
    file: UTF-8
  file:
    name: ${spring.application.name}_${spring.application.version}_log.log

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8082


heat-point:
  base-url: https://weibo.com
  cookie-string: "XSRF-TOKEN=O8FlBz255V1awMvjtHQh2ZOd; _s_tentry=www.baidu.com; UOR=www.baidu.com,open.weibo.com,www.baidu.com; Apache=3600856565491.366.1748323006418; SINAGLOBAL=3600856565491.366.1748323006418; ULV=1748323006423:1:1:1:3600856565491.366.1748323006418:; SCF=At_uHy0mJO7o4Y4rARVkp1NYl6BZQkDIdynz9m2DUD9zyhN9JyPInPrriDtiwXvMk-ujnBPsiEBnx7B67n5631c.; SUB=_2A25FMTxWDeRhGeFL7FMX9izPyzuIHXVmTzGerDV8PUNbmtAbLWL_kW9NfdRmYDvFpmURq9cSNLYNLqiHVeyEHtpo; SUBP=0033WrSXqPxfM725Ws9jqgMF55529P9D9WFuh-A6BWLKAHX9hMMwGTBY5JpX5KzhUgL.FoMfS02cSoz0ehM2dJLoIpeLxK.L1KnL12-LxKML1hzL12H4; ALF=02_1750915334; WBPSESS=Dt2hbAUaXfkVprjyrAZT_P2eVZnXPh0MY6e1nlS9e2RV185KZSYgO1SKLTco16N_nM4xVOACT1A8CJ568vqh-lipmknun117qG0t7q3nnkjkekPwaskSCm-9IOwrFjVYvBtp6ZW2Cg-SmHbCiO0m42yEjPZ0E6FZ_b1NjTYN5BEl6Cq3oTBDc0vRg_a4YVEPxbFS_b_2ikHfzrKQkpXihQ=="

